# golangci-lint configuration for GoFast service-core
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - tmp
    - vendor
    - testdata
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  # Errcheck checks for unchecked errors
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close

  # Exhaustive checks switch statements for exhaustiveness
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  # Funlen checks function length
  funlen:
    lines: 100
    statements: 50

  # Gocognit calculates cognitive complexity
  gocognit:
    min-complexity: 15

  # Goconst finds repeated strings that could be replaced by a constant
  goconst:
    min-len: 3
    min-occurrences: 3
    match-constant: true
    numbers: false
    ignore-tests: true

  # Gocritic provides diagnostics that check for bugs, performance and style issues
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  # Gocyclo calculates cyclomatic complexities
  gocyclo:
    min-complexity: 15

  # Godot checks if comments end in a period
  godot:
    scope: declarations
    exclude:
      - "^fixme:"
      - "^todo:"
    period: true
    capital: true

  # Gofmt checks whether code was gofmt-ed
  gofmt:
    simplify: true

  # Gofumpt checks whether code was gofumpt-ed
  gofumpt:
    lang-version: "1.21"
    extra-rules: true

  # Goheader checks if file header matches to pattern
  goheader:
    values:
      const:
        COMPANY: GoFast
      regexp:
        AUTHOR: ".*"
    template: |-
      Copyright (c) {{ YEAR }} {{ COMPANY }}
      Author: {{ AUTHOR }}

  # Goimports checks import grouping and formatting
  goimports:
    local-prefixes: service-core

  # Gomnd detects magic numbers
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "24"
      - "60"
      - "100"
      - "200"
      - "400"
      - "401"
      - "404"
      - "500"
      - "1000"
      - "1024"

  # Gomodguard allows to block direct usage of modules
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
            reason: "Use standard library errors or fmt.Errorf"

  # Gosec inspects source code for security problems
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked
      - G204 # Subprocess launched with variable
    exclude-generated: true

  # Govet examines Go source code and reports suspicious constructs
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf

  # Lll reports long lines
  lll:
    line-length: 120
    tab-width: 4

  # Misspell finds commonly misspelled English words in comments
  misspell:
    locale: US
    ignore-words:
      - "cancelled"

  # Nakedret finds naked returns in functions greater than a specified function length
  nakedret:
    max-func-lines: 30

  # Nestif reports deeply nested if statements
  nestif:
    min-complexity: 5

  # Noctx finds sending http request without context.Context
  noctx:
    require-ctx: true

  # Prealloc finds slice declarations that could potentially be pre-allocated
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Predeclared finds code that shadows one of Go's predeclared identifiers
  predeclared:
    ignore: ""
    q: false

  # Revive provides a framework for development of custom rules
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  # Staticcheck is a go vet on steroids
  staticcheck:
    go: "1.21"
    checks: ["all"]

  # Stylecheck is a replacement for golint
  stylecheck:
    go: "1.21"
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - fmt
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "JWT", "API"]
    http-status-code-whitelist: ["200", "400", "404", "500"]

  # Testpackage makes sure that separate _test packages are used
  testpackage:
    skip-regexp: "(export|internal)_test\\.go"

  # Unparam reports unused function parameters
  unparam:
    check-exported: false

  # Unused finds unused constants, variables, functions and types
  unused:
    go: "1.21"

  # Whitespace tool fixes leading and trailing whitespace
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Additional linters
    - asciicheck      # Simple linter to check that your code does not contain non-ASCII identifiers
    - bidichk         # Checks for dangerous unicode character sequences
    - bodyclose       # Checks whether HTTP response body is closed successfully
    - contextcheck    # Check the function whether use a non-inherited context
    - durationcheck   # Check for two durations multiplied together
    - errname         # Checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint       # Errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exhaustive      # Check exhaustiveness of enum switch statements
    - exportloopref   # Checks for pointers to enclosing loop variables
    - forbidigo       # Forbids identifiers
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid
    - gochecknoglobals # Check that no global variables exist
    - gochecknoinits  # Checks that no init functions are present in Go code
    - gocognit        # Computes and checks the cognitive complexity of functions
    - goconst         # Finds repeated strings that could be replaced by a constant
    - gocritic        # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo         # Computes and checks the cyclomatic complexity of functions
    - godot           # Check if comments end in a period
    - gofmt           # Gofmt checks whether code was gofmt-ed
    - gofumpt         # Gofumpt checks whether code was gofumpt-ed
    - goheader        # Checks is file header matches to pattern
    - goimports       # In addition to fixing imports, goimports also formats your code in the same style as gofmt
    - gomnd           # An analyzer to detect magic numbers
    - gomodguard      # Allow and block list linter for direct Go module dependencies
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - gosec           # Inspects source code for security problems
    - lll             # Reports long lines
    - makezero        # Finds slice declarations with non-zero initial length
    - misspell        # Finds commonly misspelled English words in comments
    - nakedret        # Finds naked returns in functions greater than a specified function length
    - nestif          # Reports deeply nested if statements
    - nilerr          # Finds the code that returns nil even if it checks that the error is not nil
    - noctx           # Noctx finds sending http request without context.Context
    - nolintlint      # Reports ill-formed or insufficient nolint directives
    - prealloc        # Finds slice declarations that could potentially be pre-allocated
    - predeclared     # Find code that shadows one of Go's predeclared identifiers
    - revive          # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck    # Checks whether Err of rows is checked successfully
    - sqlclosecheck   # Checks that sql.Rows and sql.Stmt are closed
    - stylecheck      # Stylecheck is a replacement for golint
    - testpackage     # Linter that makes you use a separate _test package
    - thelper         # Thelper detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - tparallel       # Tparallel detects inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters
    - wastedassign    # Wastedassign finds wasted assignment statements
    - whitespace      # Tool fixes leading and trailing whitespace

  disable:
    - cyclop          # Checks function and package cyclomatic complexity
    - decorder        # Check declaration order and count of types, constants, variables and functions
    - depguard        # Go linter that checks if package imports are in a list of acceptable packages
    - dogsled         # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - dupl            # Tool for code clone detection
    - dupword         # Checks for duplicate words in the source code
    - exhaustivestruct # Checks if all struct's fields are initialized
    - exhaustruct     # Checks if all structure fields are initialized
    - forcetypeassert # Finds forced type assertions
    - funlen          # Tool for detection of long functions
    - gci             # Gci controls golang package import order and makes it always deterministic
    - ginkgolinter    # Enforces standards of using ginkgo and gomega
    - godox           # Tool for detection of FIXME, TODO and other comment keywords
    - goerr113        # Golang linter to check the errors handling expressions
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - grouper         # An analyzer to analyze expression groups
    - importas        # Enforces consistent import aliases
    - interfacebloat  # A linter that checks the number of methods inside an interface
    - ireturn         # Accept Interfaces, Return Concrete Types
    - maintidx        # Maintidx measures the maintainability index of each function
    - nlreturn        # Nlreturn checks for a new line before return and branch statements to increase code clarity
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL
    - paralleltest    # Paralleltest detects missing usage of t.Parallel() method in your Go test
    - promlinter      # Check Prometheus metrics naming via promlinter
    - reassign        # Checks that package variables are not reassigned
    - tagliatelle     # Checks the struct tags
    - testableexamples # Linter checks if examples are testable (have an expected output)
    - varnamelen      # Checks that the length of a variable's name matches its scope
    - wrapcheck       # Checks that errors returned from external packages are wrapped
    - wsl             # Whitespace Linter - Forces you to use empty lines!

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - noctx
        - gosec

    # Exclude some linters from running on mock files
    - path: _mock\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - unused
        - deadcode

    # Exclude some linters from running on generated files
    - path: \.pb\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - lll

    # Disable line length check for long struct tags
    - linters:
        - lll
      source: "^\\s*`"

    # Disable magic number detection for HTTP status codes
    - linters:
        - gomnd
      text: "Magic number.*[4-5][0-9][0-9]"

    # Disable specific gosec rules
    - linters:
        - gosec
      text: "G404:"  # Use of weak random number generator

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - misspell
        - lll
        - whitespace
      severity: warning