/**
 * E-commerce Intake Template
 *
 * Specialized questionnaire for e-commerce projects. Covers products,
 * payment processing, shipping, inventory, and platform integrations.
 */
import type { FormSchema } from "$lib/types/form-builder";

export const ecommerceIntakeTemplate: FormSchema = {
	version: "1.0",
	steps: [
		// Section 1: Business & Contact
		{
			id: "business",
			title: "Business Information",
			description: "Tell us about your business.",
			fields: [
				{
					id: "contact_name",
					type: "text",
					name: "contact_name",
					label: "Contact Name",
					placeholder: "John Smith",
					required: true,
					layout: { width: "half", order: 1 },
				},
				{
					id: "email",
					type: "email",
					name: "email",
					label: "Email Address",
					placeholder: "john@company.com",
					required: true,
					layout: { width: "half", order: 2 },
				},
				{
					id: "business_name",
					type: "text",
					name: "business_name",
					label: "Business Name",
					placeholder: "Your Store Pty Ltd",
					required: true,
					layout: { width: "half", order: 3 },
				},
				{
					id: "phone",
					type: "tel",
					name: "phone",
					label: "Phone Number",
					placeholder: "04XX XXX XXX",
					required: false,
					layout: { width: "half", order: 4 },
				},
				{
					id: "current_website",
					type: "text",
					name: "current_website",
					label: "Current Website (if any)",
					placeholder: "www.yourstore.com",
					required: false,
					layout: { width: "full", order: 5 },
				},
				{
					id: "business_stage",
					type: "select",
					name: "business_stage",
					label: "Business Stage",
					required: true,
					options: [
						{ value: "new", label: "New business - first online store" },
						{ value: "existing_new_store", label: "Existing business - first online store" },
						{ value: "migration", label: "Migrating from another platform" },
						{ value: "redesign", label: "Redesigning existing store" },
					],
					layout: { width: "full", order: 6 },
				},
			],
		},

		// Section 2: Products
		{
			id: "products",
			title: "Products & Catalog",
			description: "Tell us about what you're selling.",
			fields: [
				{
					id: "product_types",
					type: "multiselect",
					name: "product_types",
					label: "What type of products?",
					required: true,
					options: [
						{ value: "physical", label: "Physical products" },
						{ value: "digital", label: "Digital downloads" },
						{ value: "services", label: "Services" },
						{ value: "subscriptions", label: "Subscriptions" },
						{ value: "memberships", label: "Memberships" },
						{ value: "courses", label: "Online courses" },
					],
					layout: { width: "full", order: 1 },
				},
				{
					id: "product_count",
					type: "select",
					name: "product_count",
					label: "How many products/SKUs?",
					required: true,
					options: [
						{ value: "under_25", label: "Under 25" },
						{ value: "25_100", label: "25 - 100" },
						{ value: "100_500", label: "100 - 500" },
						{ value: "500_1000", label: "500 - 1,000" },
						{ value: "over_1000", label: "Over 1,000" },
					],
					layout: { width: "half", order: 2 },
				},
				{
					id: "product_variants",
					type: "radio",
					name: "product_variants",
					label: "Do products have variants (size, color, etc.)?",
					required: true,
					options: [
						{ value: "yes", label: "Yes" },
						{ value: "no", label: "No" },
						{ value: "some", label: "Some products" },
					],
					layout: { width: "half", order: 3 },
				},
				{
					id: "product_categories",
					type: "textarea",
					name: "product_categories",
					label: "Main Product Categories",
					placeholder: "List your main product categories...",
					required: true,
					layout: { width: "full", order: 4 },
				},
				{
					id: "pricing_model",
					type: "multiselect",
					name: "pricing_model",
					label: "Pricing Model",
					required: true,
					options: [
						{ value: "fixed", label: "Fixed pricing" },
						{ value: "tiered", label: "Tiered/volume pricing" },
						{ value: "wholesale", label: "Wholesale pricing" },
						{ value: "member_pricing", label: "Member-only pricing" },
						{ value: "quote", label: "Request a quote" },
					],
					layout: { width: "full", order: 5 },
				},
			],
		},

		// Section 3: Payment & Checkout
		{
			id: "payment",
			title: "Payment & Checkout",
			description: "How will customers pay?",
			fields: [
				{
					id: "payment_methods",
					type: "multiselect",
					name: "payment_methods",
					label: "Required Payment Methods",
					required: true,
					options: [
						{ value: "credit_card", label: "Credit/Debit Cards" },
						{ value: "paypal", label: "PayPal" },
						{ value: "afterpay", label: "Afterpay" },
						{ value: "klarna", label: "Klarna" },
						{ value: "apple_pay", label: "Apple Pay" },
						{ value: "google_pay", label: "Google Pay" },
						{ value: "bank_transfer", label: "Bank Transfer" },
						{ value: "crypto", label: "Cryptocurrency" },
					],
					layout: { width: "full", order: 1 },
				},
				{
					id: "payment_processor",
					type: "select",
					name: "payment_processor",
					label: "Preferred Payment Processor",
					required: false,
					options: [
						{ value: "stripe", label: "Stripe" },
						{ value: "square", label: "Square" },
						{ value: "paypal", label: "PayPal Commerce" },
						{ value: "braintree", label: "Braintree" },
						{ value: "authorize", label: "Authorize.net" },
						{ value: "no_preference", label: "No preference" },
						{ value: "other", label: "Other" },
					],
					layout: { width: "full", order: 2 },
				},
				{
					id: "currencies",
					type: "multiselect",
					name: "currencies",
					label: "Currencies",
					required: true,
					options: [
						{ value: "aud", label: "AUD - Australian Dollar" },
						{ value: "usd", label: "USD - US Dollar" },
						{ value: "eur", label: "EUR - Euro" },
						{ value: "gbp", label: "GBP - British Pound" },
						{ value: "nzd", label: "NZD - New Zealand Dollar" },
					],
					layout: { width: "full", order: 3 },
				},
				{
					id: "checkout_features",
					type: "multiselect",
					name: "checkout_features",
					label: "Checkout Features Needed",
					required: false,
					options: [
						{ value: "guest_checkout", label: "Guest checkout" },
						{ value: "one_page", label: "One-page checkout" },
						{ value: "saved_cards", label: "Save payment methods" },
						{ value: "gift_cards", label: "Gift cards" },
						{ value: "discount_codes", label: "Discount codes" },
						{ value: "order_notes", label: "Order notes" },
					],
					layout: { width: "full", order: 4 },
				},
			],
		},

		// Section 4: Shipping & Fulfillment
		{
			id: "shipping",
			title: "Shipping & Fulfillment",
			description: "How will orders be fulfilled?",
			fields: [
				{
					id: "ships_physical",
					type: "radio",
					name: "ships_physical",
					label: "Do you ship physical products?",
					required: true,
					options: [
						{ value: "yes", label: "Yes" },
						{ value: "no", label: "No - digital only" },
						{ value: "both", label: "Both physical and digital" },
					],
					layout: { width: "full", order: 1 },
				},
				{
					id: "shipping_regions",
					type: "multiselect",
					name: "shipping_regions",
					label: "Shipping Regions",
					required: false,
					options: [
						{ value: "local", label: "Local/metro only" },
						{ value: "national", label: "Australia-wide" },
						{ value: "nz", label: "New Zealand" },
						{ value: "asia_pacific", label: "Asia Pacific" },
						{ value: "usa_canada", label: "USA/Canada" },
						{ value: "europe", label: "Europe" },
						{ value: "worldwide", label: "Worldwide" },
					],
					conditionalLogic: [
						{
							field: "ships_physical",
							operator: "notEquals",
							value: "no",
							action: "show",
						},
					],
					layout: { width: "full", order: 2 },
				},
				{
					id: "shipping_carriers",
					type: "multiselect",
					name: "shipping_carriers",
					label: "Preferred Shipping Carriers",
					required: false,
					options: [
						{ value: "auspost", label: "Australia Post" },
						{ value: "sendle", label: "Sendle" },
						{ value: "dhl", label: "DHL" },
						{ value: "fedex", label: "FedEx" },
						{ value: "ups", label: "UPS" },
						{ value: "courier", label: "Local courier" },
						{ value: "pickup", label: "Click & Collect" },
					],
					conditionalLogic: [
						{
							field: "ships_physical",
							operator: "notEquals",
							value: "no",
							action: "show",
						},
					],
					layout: { width: "full", order: 3 },
				},
				{
					id: "fulfillment_method",
					type: "select",
					name: "fulfillment_method",
					label: "Fulfillment Method",
					required: false,
					options: [
						{ value: "self", label: "Self-fulfilled" },
						{ value: "3pl", label: "Third-party logistics (3PL)" },
						{ value: "dropship", label: "Dropshipping" },
						{ value: "mixed", label: "Mixed" },
					],
					conditionalLogic: [
						{
							field: "ships_physical",
							operator: "notEquals",
							value: "no",
							action: "show",
						},
					],
					layout: { width: "full", order: 4 },
				},
			],
		},

		// Section 5: Integrations & Timeline
		{
			id: "integrations",
			title: "Integrations & Timeline",
			description: "Technical requirements and project timeline.",
			fields: [
				{
					id: "integrations_needed",
					type: "multiselect",
					name: "integrations_needed",
					label: "Required Integrations",
					required: false,
					options: [
						{ value: "accounting", label: "Accounting (Xero, MYOB, QuickBooks)" },
						{ value: "inventory", label: "Inventory management" },
						{ value: "erp", label: "ERP system" },
						{ value: "crm", label: "CRM" },
						{ value: "email_marketing", label: "Email marketing (Mailchimp, Klaviyo)" },
						{ value: "social", label: "Social media selling" },
						{ value: "marketplace", label: "Marketplaces (eBay, Amazon)" },
						{ value: "reviews", label: "Reviews platform" },
						{ value: "loyalty", label: "Loyalty/rewards program" },
					],
					layout: { width: "full", order: 1 },
				},
				{
					id: "current_systems",
					type: "textarea",
					name: "current_systems",
					label: "Current Systems/Software",
					placeholder: "List any systems you currently use that need to integrate...",
					required: false,
					layout: { width: "full", order: 2 },
				},
				{
					id: "budget_range",
					type: "select",
					name: "budget_range",
					label: "Budget Range",
					required: true,
					options: [
						{ value: "under_5k", label: "Under $5,000" },
						{ value: "5k_10k", label: "$5,000 - $10,000" },
						{ value: "10k_25k", label: "$10,000 - $25,000" },
						{ value: "25k_50k", label: "$25,000 - $50,000" },
						{ value: "over_50k", label: "Over $50,000" },
					],
					layout: { width: "half", order: 3 },
				},
				{
					id: "timeline",
					type: "select",
					name: "timeline",
					label: "Target Launch",
					required: true,
					options: [
						{ value: "asap", label: "ASAP" },
						{ value: "1_2_months", label: "1-2 months" },
						{ value: "3_4_months", label: "3-4 months" },
						{ value: "6_months", label: "6+ months" },
						{ value: "flexible", label: "Flexible" },
					],
					layout: { width: "half", order: 4 },
				},
				{
					id: "additional_notes",
					type: "textarea",
					name: "additional_notes",
					label: "Additional Information",
					placeholder: "Any other details about your e-commerce project?",
					required: false,
					layout: { width: "full", order: 5 },
				},
			],
		},
	],
	uiConfig: {
		layout: "wizard",
		showProgressBar: true,
		showStepNumbers: true,
		submitButtonText: "Submit E-commerce Brief",
		successMessage:
			"Thank you! We'll review your e-commerce requirements and prepare a detailed proposal for your online store.",
	},
	formOverrides: {
		layout: {
			maxWidth: "1200px",
		},
		header: {
			title: "E-commerce Project Brief",
			subtitle: "Help us understand your online store requirements",
			showLogo: true,
		},
		footer: {
			showPoweredBy: true,
		},
	},
};

export default ecommerceIntakeTemplate;
