// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Consultation struct {
	ID               uuid.UUID       `json:"id"`
	Created          time.Time       `json:"created"`
	Updated          time.Time       `json:"updated"`
	UserID           uuid.UUID       `json:"user_id"`
	BusinessName     string          `json:"business_name"`
	ContactName      string          `json:"contact_name"`
	ContactTitle     string          `json:"contact_title"`
	Email            string          `json:"email"`
	Phone            string          `json:"phone"`
	Website          string          `json:"website"`
	PreferredContact string          `json:"preferred_contact"`
	Industry         string          `json:"industry"`
	Location         string          `json:"location"`
	YearsInBusiness  sql.NullInt32   `json:"years_in_business"`
	TeamSize         sql.NullInt32   `json:"team_size"`
	MonthlyTraffic   sql.NullInt32   `json:"monthly_traffic"`
	CurrentPlatform  string          `json:"current_platform"`
	BusinessData     json.RawMessage `json:"business_data"`
	Challenges       json.RawMessage `json:"challenges"`
	Goals            json.RawMessage `json:"goals"`
	Budget           json.RawMessage `json:"budget"`
	ConsultationDate sql.NullTime    `json:"consultation_date"`
	DurationMinutes  sql.NullInt32   `json:"duration_minutes"`
	SalesRep         string          `json:"sales_rep"`
	Notes            string          `json:"notes"`
	NextSteps        json.RawMessage `json:"next_steps"`
	CommitmentLevel  sql.NullInt32   `json:"commitment_level"`
	Status           string          `json:"status"`
}

type ConsultationDraft struct {
	ID             uuid.UUID       `json:"id"`
	ConsultationID uuid.UUID       `json:"consultation_id"`
	UserID         uuid.UUID       `json:"user_id"`
	DraftData      json.RawMessage `json:"draft_data"`
	Created        time.Time       `json:"created"`
	Updated        time.Time       `json:"updated"`
}

type ConsultationVersion struct {
	ID                uuid.UUID       `json:"id"`
	ConsultationID    uuid.UUID       `json:"consultation_id"`
	UserID            uuid.UUID       `json:"user_id"`
	VersionNumber     int32           `json:"version_number"`
	VersionData       json.RawMessage `json:"version_data"`
	ChangeDescription string          `json:"change_description"`
	Created           time.Time       `json:"created"`
}

type Email struct {
	ID           uuid.UUID `json:"id"`
	Created      time.Time `json:"created"`
	Updated      time.Time `json:"updated"`
	UserID       uuid.UUID `json:"user_id"`
	EmailTo      string    `json:"email_to"`
	EmailFrom    string    `json:"email_from"`
	EmailSubject string    `json:"email_subject"`
	EmailBody    string    `json:"email_body"`
}

type EmailAttachment struct {
	ID          uuid.UUID `json:"id"`
	Created     time.Time `json:"created"`
	EmailID     uuid.UUID `json:"email_id"`
	FileName    string    `json:"file_name"`
	ContentType string    `json:"content_type"`
}

type File struct {
	ID          uuid.UUID `json:"id"`
	Created     time.Time `json:"created"`
	Updated     time.Time `json:"updated"`
	UserID      uuid.UUID `json:"user_id"`
	FileKey     string    `json:"file_key"`
	FileName    string    `json:"file_name"`
	FileSize    int64     `json:"file_size"`
	ContentType string    `json:"content_type"`
}

type Note struct {
	ID       uuid.UUID `json:"id"`
	Created  time.Time `json:"created"`
	Updated  time.Time `json:"updated"`
	UserID   uuid.UUID `json:"user_id"`
	Title    string    `json:"title"`
	Category string    `json:"category"`
	Content  string    `json:"content"`
}

type Token struct {
	ID       string    `json:"id"`
	Expires  time.Time `json:"expires"`
	Target   string    `json:"target"`
	Callback string    `json:"callback"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Created         time.Time `json:"created"`
	Updated         time.Time `json:"updated"`
	Email           string    `json:"email"`
	Phone           string    `json:"phone"`
	Access          int64     `json:"access"`
	Sub             string    `json:"sub"`
	Avatar          string    `json:"avatar"`
	CustomerID      string    `json:"customer_id"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	ApiKey          string    `json:"api_key"`
}
