// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"time"

	"github.com/google/uuid"
)

type Email struct {
	ID           uuid.UUID `json:"id"`
	Created      time.Time `json:"created"`
	Updated      time.Time `json:"updated"`
	UserID       uuid.UUID `json:"user_id"`
	EmailTo      string    `json:"email_to"`
	EmailFrom    string    `json:"email_from"`
	EmailSubject string    `json:"email_subject"`
	EmailBody    string    `json:"email_body"`
}

type EmailAttachment struct {
	ID          uuid.UUID `json:"id"`
	Created     time.Time `json:"created"`
	EmailID     uuid.UUID `json:"email_id"`
	FileName    string    `json:"file_name"`
	ContentType string    `json:"content_type"`
}

type File struct {
	ID          uuid.UUID `json:"id"`
	Created     time.Time `json:"created"`
	Updated     time.Time `json:"updated"`
	UserID      uuid.UUID `json:"user_id"`
	FileKey     string    `json:"file_key"`
	FileName    string    `json:"file_name"`
	FileSize    int64     `json:"file_size"`
	ContentType string    `json:"content_type"`
}

type Note struct {
	ID       uuid.UUID `json:"id"`
	Created  time.Time `json:"created"`
	Updated  time.Time `json:"updated"`
	UserID   uuid.UUID `json:"user_id"`
	Title    string    `json:"title"`
	Category string    `json:"category"`
	Content  string    `json:"content"`
}

type Token struct {
	ID       string    `json:"id"`
	Expires  time.Time `json:"expires"`
	Target   string    `json:"target"`
	Callback string    `json:"callback"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Created         time.Time `json:"created"`
	Updated         time.Time `json:"updated"`
	Email           string    `json:"email"`
	Phone           string    `json:"phone"`
	Access          int64     `json:"access"`
	Sub             string    `json:"sub"`
	Avatar          string    `json:"avatar"`
	CustomerID      string    `json:"customer_id"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	ApiKey          string    `json:"api_key"`
}
