// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Consultation queries
	CountConsultations(ctx context.Context, userID uuid.UUID) (int64, error)
	CountNotes(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteConsultation(ctx context.Context, id uuid.UUID) error
	DeleteConsultationDraft(ctx context.Context, arg DeleteConsultationDraftParams) error
	DeleteConsultationVersions(ctx context.Context, consultationID uuid.UUID) error
	DeleteFile(ctx context.Context, id uuid.UUID) error
	DeleteNote(ctx context.Context, id uuid.UUID) error
	DeleteTokens(ctx context.Context) error
	GetLatestVersionNumber(ctx context.Context, consultationID uuid.UUID) (interface{}, error)
	InsertConsultation(ctx context.Context, arg InsertConsultationParams) (Consultation, error)
	InsertConsultationDraft(ctx context.Context, arg InsertConsultationDraftParams) (ConsultationDraft, error)
	InsertConsultationVersion(ctx context.Context, arg InsertConsultationVersionParams) (ConsultationVersion, error)
	InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error)
	InsertEmailAttachment(ctx context.Context, arg InsertEmailAttachmentParams) (EmailAttachment, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	SelectConsultation(ctx context.Context, id uuid.UUID) (Consultation, error)
	// Consultation Draft queries
	SelectConsultationDraft(ctx context.Context, arg SelectConsultationDraftParams) (ConsultationDraft, error)
	SelectConsultationVersion(ctx context.Context, arg SelectConsultationVersionParams) (ConsultationVersion, error)
	// Consultation Version queries
	SelectConsultationVersions(ctx context.Context, consultationID uuid.UUID) ([]ConsultationVersion, error)
	SelectConsultations(ctx context.Context, arg SelectConsultationsParams) ([]Consultation, error)
	SelectConsultationsByStatus(ctx context.Context, arg SelectConsultationsByStatusParams) ([]Consultation, error)
	SelectEmailAttachments(ctx context.Context, emailID uuid.UUID) ([]EmailAttachment, error)
	SelectEmails(ctx context.Context, userID uuid.UUID) ([]Email, error)
	SelectFile(ctx context.Context, id uuid.UUID) (File, error)
	SelectFiles(ctx context.Context, userID uuid.UUID) ([]File, error)
	SelectNote(ctx context.Context, id uuid.UUID) (Note, error)
	SelectNotes(ctx context.Context, arg SelectNotesParams) ([]Note, error)
	SelectToken(ctx context.Context, id string) (Token, error)
	SelectUser(ctx context.Context, id uuid.UUID) (User, error)
	SelectUserByCustomerID(ctx context.Context, customerID string) (User, error)
	SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error)
	SelectUsers(ctx context.Context) ([]User, error)
	UpdateConsultation(ctx context.Context, arg UpdateConsultationParams) (Consultation, error)
	UpdateConsultationDraft(ctx context.Context, arg UpdateConsultationDraftParams) (ConsultationDraft, error)
	UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error)
	UpdateUserActivity(ctx context.Context, id uuid.UUID) error
	UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
	UpsertConsultationDraft(ctx context.Context, arg UpsertConsultationDraftParams) (ConsultationDraft, error)
}

var _ Querier = (*Queries)(nil)
