// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupOldDrafts(ctx context.Context, updatedAt time.Time) error
	CountConsultationVersions(ctx context.Context, consultationID uuid.UUID) (int64, error)
	CountConsultationsByStatus(ctx context.Context, arg CountConsultationsByStatusParams) (int64, error)
	CountConsultationsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountNotes(ctx context.Context, userID uuid.UUID) (int64, error)
	// Consultation queries (New Schema)
	// Basic CRUD operations for consultations
	CreateConsultation(ctx context.Context, arg CreateConsultationParams) (Consultation, error)
	// Draft management queries
	CreateConsultationDraft(ctx context.Context, arg CreateConsultationDraftParams) (ConsultationDraft, error)
	// Version tracking queries
	CreateConsultationVersion(ctx context.Context, arg CreateConsultationVersionParams) (ConsultationVersion, error)
	DeleteConsultation(ctx context.Context, id uuid.UUID) error
	DeleteConsultationDraft(ctx context.Context, consultationID uuid.UUID) error
	DeleteConsultationDraftByUser(ctx context.Context, arg DeleteConsultationDraftByUserParams) error
	DeleteConsultationVersions(ctx context.Context, consultationID uuid.UUID) error
	DeleteFile(ctx context.Context, id uuid.UUID) error
	DeleteNote(ctx context.Context, id uuid.UUID) error
	DeleteSubscription(ctx context.Context, stripeSubscriptionID string) error
	DeleteTokens(ctx context.Context) error
	GetConsultation(ctx context.Context, id uuid.UUID) (Consultation, error)
	GetConsultationByUser(ctx context.Context, arg GetConsultationByUserParams) (Consultation, error)
	GetConsultationDraft(ctx context.Context, consultationID uuid.UUID) (ConsultationDraft, error)
	GetConsultationDraftByUser(ctx context.Context, arg GetConsultationDraftByUserParams) (ConsultationDraft, error)
	GetConsultationVersion(ctx context.Context, arg GetConsultationVersionParams) (ConsultationVersion, error)
	// JSONB field queries for advanced filtering
	GetConsultationsByBusinessName(ctx context.Context, arg GetConsultationsByBusinessNameParams) ([]Consultation, error)
	GetConsultationsByIndustry(ctx context.Context, arg GetConsultationsByIndustryParams) ([]Consultation, error)
	GetConsultationsByUrgency(ctx context.Context, arg GetConsultationsByUrgencyParams) ([]Consultation, error)
	GetLatestConsultationVersion(ctx context.Context, consultationID uuid.UUID) (ConsultationVersion, error)
	GetNextVersionNumber(ctx context.Context, consultationID uuid.UUID) (int32, error)
	InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error)
	InsertEmailAttachment(ctx context.Context, arg InsertEmailAttachmentParams) (EmailAttachment, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	ListConsultationVersions(ctx context.Context, arg ListConsultationVersionsParams) ([]ConsultationVersion, error)
	ListConsultationsByCompletion(ctx context.Context, arg ListConsultationsByCompletionParams) ([]Consultation, error)
	ListConsultationsByDateRange(ctx context.Context, arg ListConsultationsByDateRangeParams) ([]Consultation, error)
	ListConsultationsByStatus(ctx context.Context, arg ListConsultationsByStatusParams) ([]Consultation, error)
	// Consultation listing and filtering
	ListConsultationsByUser(ctx context.Context, arg ListConsultationsByUserParams) ([]Consultation, error)
	SearchConsultations(ctx context.Context, arg SearchConsultationsParams) ([]Consultation, error)
	SelectEmailAttachments(ctx context.Context, emailID uuid.UUID) ([]EmailAttachment, error)
	SelectEmails(ctx context.Context, userID uuid.UUID) ([]Email, error)
	SelectFile(ctx context.Context, id uuid.UUID) (File, error)
	SelectFiles(ctx context.Context, userID uuid.UUID) ([]File, error)
	SelectNote(ctx context.Context, id uuid.UUID) (Note, error)
	SelectNotes(ctx context.Context, arg SelectNotesParams) ([]Note, error)
	SelectSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (Subscription, error)
	// Subscription queries
	SelectSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (Subscription, error)
	SelectSubscriptionsByCustomerID(ctx context.Context, stripeCustomerID string) ([]Subscription, error)
	SelectToken(ctx context.Context, id string) (Token, error)
	SelectUser(ctx context.Context, id uuid.UUID) (User, error)
	SelectUserByCustomerID(ctx context.Context, customerID string) (User, error)
	SelectUserByEmail(ctx context.Context, email string) (User, error)
	SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error)
	SelectUsers(ctx context.Context) ([]User, error)
	UpdateConsultation(ctx context.Context, arg UpdateConsultationParams) (Consultation, error)
	UpdateConsultationDraft(ctx context.Context, arg UpdateConsultationDraftParams) (ConsultationDraft, error)
	UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error)
	UpdateUserActivity(ctx context.Context, id uuid.UUID) error
	UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserSub(ctx context.Context, arg UpdateUserSubParams) error
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
	UpsertConsultationDraft(ctx context.Context, arg UpsertConsultationDraftParams) (ConsultationDraft, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
