// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_postgres.sql

package query

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countConsultations = `-- name: CountConsultations :one

select count(*) from consultations where user_id = $1
`

// Consultation queries
func (q *Queries) CountConsultations(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConsultations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotes = `-- name: CountNotes :one
select count(*) from notes where user_id = $1
`

func (q *Queries) CountNotes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConsultation = `-- name: DeleteConsultation :exec
delete from consultations where id = $1
`

func (q *Queries) DeleteConsultation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConsultation, id)
	return err
}

const deleteConsultationDraft = `-- name: DeleteConsultationDraft :exec
delete from consultation_drafts where consultation_id = $1 and user_id = $2
`

type DeleteConsultationDraftParams struct {
	ConsultationID uuid.UUID `json:"consultation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteConsultationDraft(ctx context.Context, arg DeleteConsultationDraftParams) error {
	_, err := q.db.ExecContext(ctx, deleteConsultationDraft, arg.ConsultationID, arg.UserID)
	return err
}

const deleteConsultationVersions = `-- name: DeleteConsultationVersions :exec
delete from consultation_versions where consultation_id = $1
`

func (q *Queries) DeleteConsultationVersions(ctx context.Context, consultationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConsultationVersions, consultationID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
delete from files where id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
delete from notes where id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteTokens = `-- name: DeleteTokens :exec
delete from tokens where expires < current_timestamp
`

func (q *Queries) DeleteTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTokens)
	return err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
select coalesce(max(version_number), 0) from consultation_versions where consultation_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, consultationID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, consultationID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const insertConsultation = `-- name: InsertConsultation :one
insert into consultations (
    id, user_id, business_name, contact_name, contact_title, email, phone, website,
    preferred_contact, industry, location, years_in_business, team_size, monthly_traffic,
    current_platform, business_data, challenges, goals, budget, consultation_date,
    duration_minutes, sales_rep, notes, next_steps, commitment_level, status
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26
) returning id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status
`

type InsertConsultationParams struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	BusinessName     string          `json:"business_name"`
	ContactName      string          `json:"contact_name"`
	ContactTitle     string          `json:"contact_title"`
	Email            string          `json:"email"`
	Phone            string          `json:"phone"`
	Website          string          `json:"website"`
	PreferredContact string          `json:"preferred_contact"`
	Industry         string          `json:"industry"`
	Location         string          `json:"location"`
	YearsInBusiness  sql.NullInt32   `json:"years_in_business"`
	TeamSize         sql.NullInt32   `json:"team_size"`
	MonthlyTraffic   sql.NullInt32   `json:"monthly_traffic"`
	CurrentPlatform  string          `json:"current_platform"`
	BusinessData     json.RawMessage `json:"business_data"`
	Challenges       json.RawMessage `json:"challenges"`
	Goals            json.RawMessage `json:"goals"`
	Budget           json.RawMessage `json:"budget"`
	ConsultationDate sql.NullTime    `json:"consultation_date"`
	DurationMinutes  sql.NullInt32   `json:"duration_minutes"`
	SalesRep         string          `json:"sales_rep"`
	Notes            string          `json:"notes"`
	NextSteps        json.RawMessage `json:"next_steps"`
	CommitmentLevel  sql.NullInt32   `json:"commitment_level"`
	Status           string          `json:"status"`
}

func (q *Queries) InsertConsultation(ctx context.Context, arg InsertConsultationParams) (Consultation, error) {
	row := q.db.QueryRowContext(ctx, insertConsultation,
		arg.ID,
		arg.UserID,
		arg.BusinessName,
		arg.ContactName,
		arg.ContactTitle,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.PreferredContact,
		arg.Industry,
		arg.Location,
		arg.YearsInBusiness,
		arg.TeamSize,
		arg.MonthlyTraffic,
		arg.CurrentPlatform,
		arg.BusinessData,
		arg.Challenges,
		arg.Goals,
		arg.Budget,
		arg.ConsultationDate,
		arg.DurationMinutes,
		arg.SalesRep,
		arg.Notes,
		arg.NextSteps,
		arg.CommitmentLevel,
		arg.Status,
	)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.ContactTitle,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.PreferredContact,
		&i.Industry,
		&i.Location,
		&i.YearsInBusiness,
		&i.TeamSize,
		&i.MonthlyTraffic,
		&i.CurrentPlatform,
		&i.BusinessData,
		&i.Challenges,
		&i.Goals,
		&i.Budget,
		&i.ConsultationDate,
		&i.DurationMinutes,
		&i.SalesRep,
		&i.Notes,
		&i.NextSteps,
		&i.CommitmentLevel,
		&i.Status,
	)
	return i, err
}

const insertConsultationDraft = `-- name: InsertConsultationDraft :one
insert into consultation_drafts (id, consultation_id, user_id, draft_data)
values ($1, $2, $3, $4) returning id, consultation_id, user_id, draft_data, created, updated
`

type InsertConsultationDraftParams struct {
	ID             uuid.UUID       `json:"id"`
	ConsultationID uuid.UUID       `json:"consultation_id"`
	UserID         uuid.UUID       `json:"user_id"`
	DraftData      json.RawMessage `json:"draft_data"`
}

func (q *Queries) InsertConsultationDraft(ctx context.Context, arg InsertConsultationDraftParams) (ConsultationDraft, error) {
	row := q.db.QueryRowContext(ctx, insertConsultationDraft,
		arg.ID,
		arg.ConsultationID,
		arg.UserID,
		arg.DraftData,
	)
	var i ConsultationDraft
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.DraftData,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertConsultationVersion = `-- name: InsertConsultationVersion :one
insert into consultation_versions (id, consultation_id, user_id, version_number, version_data, change_description)
values ($1, $2, $3, $4, $5, $6) returning id, consultation_id, user_id, version_number, version_data, change_description, created
`

type InsertConsultationVersionParams struct {
	ID                uuid.UUID       `json:"id"`
	ConsultationID    uuid.UUID       `json:"consultation_id"`
	UserID            uuid.UUID       `json:"user_id"`
	VersionNumber     int32           `json:"version_number"`
	VersionData       json.RawMessage `json:"version_data"`
	ChangeDescription string          `json:"change_description"`
}

func (q *Queries) InsertConsultationVersion(ctx context.Context, arg InsertConsultationVersionParams) (ConsultationVersion, error) {
	row := q.db.QueryRowContext(ctx, insertConsultationVersion,
		arg.ID,
		arg.ConsultationID,
		arg.UserID,
		arg.VersionNumber,
		arg.VersionData,
		arg.ChangeDescription,
	)
	var i ConsultationVersion
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.VersionNumber,
		&i.VersionData,
		&i.ChangeDescription,
		&i.Created,
	)
	return i, err
}

const insertEmail = `-- name: InsertEmail :one
insert into emails (id, user_id, email_to, email_from, email_subject, email_body) values ($1, $2, $3, $4, $5, $6) returning id, created, updated, user_id, email_to, email_from, email_subject, email_body
`

type InsertEmailParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	EmailTo      string    `json:"email_to"`
	EmailFrom    string    `json:"email_from"`
	EmailSubject string    `json:"email_subject"`
	EmailBody    string    `json:"email_body"`
}

func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, insertEmail,
		arg.ID,
		arg.UserID,
		arg.EmailTo,
		arg.EmailFrom,
		arg.EmailSubject,
		arg.EmailBody,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.EmailTo,
		&i.EmailFrom,
		&i.EmailSubject,
		&i.EmailBody,
	)
	return i, err
}

const insertEmailAttachment = `-- name: InsertEmailAttachment :one
insert into email_attachments (id, email_id, file_name, content_type) values ($1, $2, $3, $4) returning id, created, email_id, file_name, content_type
`

type InsertEmailAttachmentParams struct {
	ID          uuid.UUID `json:"id"`
	EmailID     uuid.UUID `json:"email_id"`
	FileName    string    `json:"file_name"`
	ContentType string    `json:"content_type"`
}

func (q *Queries) InsertEmailAttachment(ctx context.Context, arg InsertEmailAttachmentParams) (EmailAttachment, error) {
	row := q.db.QueryRowContext(ctx, insertEmailAttachment,
		arg.ID,
		arg.EmailID,
		arg.FileName,
		arg.ContentType,
	)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.EmailID,
		&i.FileName,
		&i.ContentType,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
insert into files (id, user_id, file_key, file_name, file_size, content_type) values ($1, $2, $3, $4, $5, $6) returning id, created, updated, user_id, file_key, file_name, file_size, content_type
`

type InsertFileParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	FileKey     string    `json:"file_key"`
	FileName    string    `json:"file_name"`
	FileSize    int64     `json:"file_size"`
	ContentType string    `json:"content_type"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.ID,
		arg.UserID,
		arg.FileKey,
		arg.FileName,
		arg.FileSize,
		arg.ContentType,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :one
insert into notes (id, user_id, title, category, content) values ($1, $2, $3, $4, $5) returning id, created, updated, user_id, title, category, content
`

type InsertNoteParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Title    string    `json:"title"`
	Category string    `json:"category"`
	Content  string    `json:"content"`
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, insertNote,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Category,
		arg.Content,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.Content,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :one
insert into tokens (id, expires, target, callback) values ($1, $2, $3, $4) returning id, expires, target, callback
`

type InsertTokenParams struct {
	ID       string    `json:"id"`
	Expires  time.Time `json:"expires"`
	Target   string    `json:"target"`
	Callback string    `json:"callback"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, insertToken,
		arg.ID,
		arg.Expires,
		arg.Target,
		arg.Callback,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Expires,
		&i.Target,
		&i.Callback,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, email, access, sub, avatar, api_key) values ($1, $2, $3, $4, $5, $6) returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key
`

type InsertUserParams struct {
	ID     uuid.UUID `json:"id"`
	Email  string    `json:"email"`
	Access int64     `json:"access"`
	Sub    string    `json:"sub"`
	Avatar string    `json:"avatar"`
	ApiKey string    `json:"api_key"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Access,
		arg.Sub,
		arg.Avatar,
		arg.ApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const selectConsultation = `-- name: SelectConsultation :one
select id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status from consultations where id = $1
`

func (q *Queries) SelectConsultation(ctx context.Context, id uuid.UUID) (Consultation, error) {
	row := q.db.QueryRowContext(ctx, selectConsultation, id)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.ContactTitle,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.PreferredContact,
		&i.Industry,
		&i.Location,
		&i.YearsInBusiness,
		&i.TeamSize,
		&i.MonthlyTraffic,
		&i.CurrentPlatform,
		&i.BusinessData,
		&i.Challenges,
		&i.Goals,
		&i.Budget,
		&i.ConsultationDate,
		&i.DurationMinutes,
		&i.SalesRep,
		&i.Notes,
		&i.NextSteps,
		&i.CommitmentLevel,
		&i.Status,
	)
	return i, err
}

const selectConsultationDraft = `-- name: SelectConsultationDraft :one

select id, consultation_id, user_id, draft_data, created, updated from consultation_drafts where consultation_id = $1 and user_id = $2
`

type SelectConsultationDraftParams struct {
	ConsultationID uuid.UUID `json:"consultation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// Consultation Draft queries
func (q *Queries) SelectConsultationDraft(ctx context.Context, arg SelectConsultationDraftParams) (ConsultationDraft, error) {
	row := q.db.QueryRowContext(ctx, selectConsultationDraft, arg.ConsultationID, arg.UserID)
	var i ConsultationDraft
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.DraftData,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const selectConsultationVersion = `-- name: SelectConsultationVersion :one
select id, consultation_id, user_id, version_number, version_data, change_description, created from consultation_versions where consultation_id = $1 and version_number = $2
`

type SelectConsultationVersionParams struct {
	ConsultationID uuid.UUID `json:"consultation_id"`
	VersionNumber  int32     `json:"version_number"`
}

func (q *Queries) SelectConsultationVersion(ctx context.Context, arg SelectConsultationVersionParams) (ConsultationVersion, error) {
	row := q.db.QueryRowContext(ctx, selectConsultationVersion, arg.ConsultationID, arg.VersionNumber)
	var i ConsultationVersion
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.VersionNumber,
		&i.VersionData,
		&i.ChangeDescription,
		&i.Created,
	)
	return i, err
}

const selectConsultationVersions = `-- name: SelectConsultationVersions :many

select id, consultation_id, user_id, version_number, version_data, change_description, created from consultation_versions where consultation_id = $1 order by version_number desc
`

// Consultation Version queries
func (q *Queries) SelectConsultationVersions(ctx context.Context, consultationID uuid.UUID) ([]ConsultationVersion, error) {
	rows, err := q.db.QueryContext(ctx, selectConsultationVersions, consultationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsultationVersion
	for rows.Next() {
		var i ConsultationVersion
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.UserID,
			&i.VersionNumber,
			&i.VersionData,
			&i.ChangeDescription,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectConsultations = `-- name: SelectConsultations :many
select id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status from consultations where user_id = $1 order by created desc limit $2 offset $3
`

type SelectConsultationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) SelectConsultations(ctx context.Context, arg SelectConsultationsParams) ([]Consultation, error) {
	rows, err := q.db.QueryContext(ctx, selectConsultations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.BusinessName,
			&i.ContactName,
			&i.ContactTitle,
			&i.Email,
			&i.Phone,
			&i.Website,
			&i.PreferredContact,
			&i.Industry,
			&i.Location,
			&i.YearsInBusiness,
			&i.TeamSize,
			&i.MonthlyTraffic,
			&i.CurrentPlatform,
			&i.BusinessData,
			&i.Challenges,
			&i.Goals,
			&i.Budget,
			&i.ConsultationDate,
			&i.DurationMinutes,
			&i.SalesRep,
			&i.Notes,
			&i.NextSteps,
			&i.CommitmentLevel,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectConsultationsByStatus = `-- name: SelectConsultationsByStatus :many
select id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status from consultations where user_id = $1 and status = $2 order by created desc limit $3 offset $4
`

type SelectConsultationsByStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) SelectConsultationsByStatus(ctx context.Context, arg SelectConsultationsByStatusParams) ([]Consultation, error) {
	rows, err := q.db.QueryContext(ctx, selectConsultationsByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.BusinessName,
			&i.ContactName,
			&i.ContactTitle,
			&i.Email,
			&i.Phone,
			&i.Website,
			&i.PreferredContact,
			&i.Industry,
			&i.Location,
			&i.YearsInBusiness,
			&i.TeamSize,
			&i.MonthlyTraffic,
			&i.CurrentPlatform,
			&i.BusinessData,
			&i.Challenges,
			&i.Goals,
			&i.Budget,
			&i.ConsultationDate,
			&i.DurationMinutes,
			&i.SalesRep,
			&i.Notes,
			&i.NextSteps,
			&i.CommitmentLevel,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectEmailAttachments = `-- name: SelectEmailAttachments :many
select id, created, email_id, file_name, content_type from email_attachments where email_id = $1
`

func (q *Queries) SelectEmailAttachments(ctx context.Context, emailID uuid.UUID) ([]EmailAttachment, error) {
	rows, err := q.db.QueryContext(ctx, selectEmailAttachments, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAttachment
	for rows.Next() {
		var i EmailAttachment
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.EmailID,
			&i.FileName,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectEmails = `-- name: SelectEmails :many
select id, created, updated, user_id, email_to, email_from, email_subject, email_body from emails where user_id = $1
`

func (q *Queries) SelectEmails(ctx context.Context, userID uuid.UUID) ([]Email, error) {
	rows, err := q.db.QueryContext(ctx, selectEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.EmailTo,
			&i.EmailFrom,
			&i.EmailSubject,
			&i.EmailBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFile = `-- name: SelectFile :one
select id, created, updated, user_id, file_key, file_name, file_size, content_type from files where id = $1
`

func (q *Queries) SelectFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, selectFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.FileKey,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
	)
	return i, err
}

const selectFiles = `-- name: SelectFiles :many
select id, created, updated, user_id, file_key, file_name, file_size, content_type from files where user_id = $1
`

func (q *Queries) SelectFiles(ctx context.Context, userID uuid.UUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, selectFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.FileKey,
			&i.FileName,
			&i.FileSize,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectNote = `-- name: SelectNote :one
select id, created, updated, user_id, title, category, content from notes where id = $1
`

func (q *Queries) SelectNote(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, selectNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.Content,
	)
	return i, err
}

const selectNotes = `-- name: SelectNotes :many
select id, created, updated, user_id, title, category, content from notes where user_id = $1 order by created desc limit $2 offset $3
`

type SelectNotesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) SelectNotes(ctx context.Context, arg SelectNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, selectNotes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.Title,
			&i.Category,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectToken = `-- name: SelectToken :one
select id, expires, target, callback from tokens where id = $1
`

func (q *Queries) SelectToken(ctx context.Context, id string) (Token, error) {
	row := q.db.QueryRowContext(ctx, selectToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Expires,
		&i.Target,
		&i.Callback,
	)
	return i, err
}

const selectUser = `-- name: SelectUser :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key from users where id = $1
`

func (q *Queries) SelectUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const selectUserByCustomerID = `-- name: SelectUserByCustomerID :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key from users where customer_id = $1
`

func (q *Queries) SelectUserByCustomerID(ctx context.Context, customerID string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByCustomerID, customerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const selectUserByEmailAndSub = `-- name: SelectUserByEmailAndSub :one
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key from users where email = $1 and sub = $2
`

type SelectUserByEmailAndSubParams struct {
	Email string `json:"email"`
	Sub   string `json:"sub"`
}

func (q *Queries) SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmailAndSub, arg.Email, arg.Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const selectUsers = `-- name: SelectUsers :many
select id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key from users
`

func (q *Queries) SelectUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, selectUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.Email,
			&i.Phone,
			&i.Access,
			&i.Sub,
			&i.Avatar,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.SubscriptionEnd,
			&i.ApiKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsultation = `-- name: UpdateConsultation :one
update consultations set
    business_name = $1,
    contact_name = $2,
    contact_title = $3,
    email = $4,
    phone = $5,
    website = $6,
    preferred_contact = $7,
    industry = $8,
    location = $9,
    years_in_business = $10,
    team_size = $11,
    monthly_traffic = $12,
    current_platform = $13,
    business_data = $14,
    challenges = $15,
    goals = $16,
    budget = $17,
    consultation_date = $18,
    duration_minutes = $19,
    sales_rep = $20,
    notes = $21,
    next_steps = $22,
    commitment_level = $23,
    status = $24,
    updated = current_timestamp
where id = $25 returning id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status
`

type UpdateConsultationParams struct {
	BusinessName     string          `json:"business_name"`
	ContactName      string          `json:"contact_name"`
	ContactTitle     string          `json:"contact_title"`
	Email            string          `json:"email"`
	Phone            string          `json:"phone"`
	Website          string          `json:"website"`
	PreferredContact string          `json:"preferred_contact"`
	Industry         string          `json:"industry"`
	Location         string          `json:"location"`
	YearsInBusiness  sql.NullInt32   `json:"years_in_business"`
	TeamSize         sql.NullInt32   `json:"team_size"`
	MonthlyTraffic   sql.NullInt32   `json:"monthly_traffic"`
	CurrentPlatform  string          `json:"current_platform"`
	BusinessData     json.RawMessage `json:"business_data"`
	Challenges       json.RawMessage `json:"challenges"`
	Goals            json.RawMessage `json:"goals"`
	Budget           json.RawMessage `json:"budget"`
	ConsultationDate sql.NullTime    `json:"consultation_date"`
	DurationMinutes  sql.NullInt32   `json:"duration_minutes"`
	SalesRep         string          `json:"sales_rep"`
	Notes            string          `json:"notes"`
	NextSteps        json.RawMessage `json:"next_steps"`
	CommitmentLevel  sql.NullInt32   `json:"commitment_level"`
	Status           string          `json:"status"`
	ID               uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateConsultation(ctx context.Context, arg UpdateConsultationParams) (Consultation, error) {
	row := q.db.QueryRowContext(ctx, updateConsultation,
		arg.BusinessName,
		arg.ContactName,
		arg.ContactTitle,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.PreferredContact,
		arg.Industry,
		arg.Location,
		arg.YearsInBusiness,
		arg.TeamSize,
		arg.MonthlyTraffic,
		arg.CurrentPlatform,
		arg.BusinessData,
		arg.Challenges,
		arg.Goals,
		arg.Budget,
		arg.ConsultationDate,
		arg.DurationMinutes,
		arg.SalesRep,
		arg.Notes,
		arg.NextSteps,
		arg.CommitmentLevel,
		arg.Status,
		arg.ID,
	)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.ContactTitle,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.PreferredContact,
		&i.Industry,
		&i.Location,
		&i.YearsInBusiness,
		&i.TeamSize,
		&i.MonthlyTraffic,
		&i.CurrentPlatform,
		&i.BusinessData,
		&i.Challenges,
		&i.Goals,
		&i.Budget,
		&i.ConsultationDate,
		&i.DurationMinutes,
		&i.SalesRep,
		&i.Notes,
		&i.NextSteps,
		&i.CommitmentLevel,
		&i.Status,
	)
	return i, err
}

const updateConsultationDraft = `-- name: UpdateConsultationDraft :one
update consultation_drafts set
    draft_data = $1,
    updated = current_timestamp
where consultation_id = $2 and user_id = $3 returning id, consultation_id, user_id, draft_data, created, updated
`

type UpdateConsultationDraftParams struct {
	DraftData      json.RawMessage `json:"draft_data"`
	ConsultationID uuid.UUID       `json:"consultation_id"`
	UserID         uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateConsultationDraft(ctx context.Context, arg UpdateConsultationDraftParams) (ConsultationDraft, error) {
	row := q.db.QueryRowContext(ctx, updateConsultationDraft, arg.DraftData, arg.ConsultationID, arg.UserID)
	var i ConsultationDraft
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.DraftData,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateConsultationStatus = `-- name: UpdateConsultationStatus :one
update consultations set status = $1, updated = current_timestamp where id = $2 returning id, created, updated, user_id, business_name, contact_name, contact_title, email, phone, website, preferred_contact, industry, location, years_in_business, team_size, monthly_traffic, current_platform, business_data, challenges, goals, budget, consultation_date, duration_minutes, sales_rep, notes, next_steps, commitment_level, status
`

type UpdateConsultationStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error) {
	row := q.db.QueryRowContext(ctx, updateConsultationStatus, arg.Status, arg.ID)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.ContactTitle,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.PreferredContact,
		&i.Industry,
		&i.Location,
		&i.YearsInBusiness,
		&i.TeamSize,
		&i.MonthlyTraffic,
		&i.CurrentPlatform,
		&i.BusinessData,
		&i.Challenges,
		&i.Goals,
		&i.Budget,
		&i.ConsultationDate,
		&i.DurationMinutes,
		&i.SalesRep,
		&i.Notes,
		&i.NextSteps,
		&i.CommitmentLevel,
		&i.Status,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
update notes set title = $1, category = $2, content = $3 where id = $4 returning id, created, updated, user_id, title, category, content
`

type UpdateNoteParams struct {
	Title    string    `json:"title"`
	Category string    `json:"category"`
	Content  string    `json:"content"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.Content,
	)
	return i, err
}

const updateToken = `-- name: UpdateToken :exec
update tokens set expires = $1 where id = $2 returning id, expires, target, callback
`

type UpdateTokenParams struct {
	Expires time.Time `json:"expires"`
	ID      string    `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken, arg.Expires, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
update users set 
    email = $1, 
    phone = $2, 
    access = $3, 
    avatar = $4, 
    subscription_id = $5, 
    subscription_end = $6,
    api_key = $7,
    updated = current_timestamp
where id = $8 returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key
`

type UpdateUserParams struct {
	Email           string    `json:"email"`
	Phone           string    `json:"phone"`
	Access          int64     `json:"access"`
	Avatar          string    `json:"avatar"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	ApiKey          string    `json:"api_key"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Phone,
		arg.Access,
		arg.Avatar,
		arg.SubscriptionID,
		arg.SubscriptionEnd,
		arg.ApiKey,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const updateUserAccess = `-- name: UpdateUserAccess :one
update users set access = $1 where id = $2 returning id, created, updated, email, phone, access, sub, avatar, customer_id, subscription_id, subscription_end, api_key
`

type UpdateUserAccessParams struct {
	Access int64     `json:"access"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAccess, arg.Access, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.SubscriptionEnd,
		&i.ApiKey,
	)
	return i, err
}

const updateUserActivity = `-- name: UpdateUserActivity :exec
update users set updated = current_timestamp where id = $1
`

func (q *Queries) UpdateUserActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserActivity, id)
	return err
}

const updateUserCustomerID = `-- name: UpdateUserCustomerID :exec
update users set customer_id = $1 where id = $2
`

type UpdateUserCustomerIDParams struct {
	CustomerID string    `json:"customer_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCustomerID, arg.CustomerID, arg.ID)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
update users set phone = $2 where id = $1
`

type UpdateUserPhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhone, arg.ID, arg.Phone)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
update users set access = $1, subscription_id = $2, subscription_end = $3 where customer_id = $4
`

type UpdateUserSubscriptionParams struct {
	Access          int64     `json:"access"`
	SubscriptionID  string    `json:"subscription_id"`
	SubscriptionEnd time.Time `json:"subscription_end"`
	CustomerID      string    `json:"customer_id"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscription,
		arg.Access,
		arg.SubscriptionID,
		arg.SubscriptionEnd,
		arg.CustomerID,
	)
	return err
}

const upsertConsultationDraft = `-- name: UpsertConsultationDraft :one
insert into consultation_drafts (id, consultation_id, user_id, draft_data)
values ($1, $2, $3, $4)
on conflict (consultation_id, user_id)
do update set
    draft_data = excluded.draft_data,
    updated = current_timestamp
returning id, consultation_id, user_id, draft_data, created, updated
`

type UpsertConsultationDraftParams struct {
	ID             uuid.UUID       `json:"id"`
	ConsultationID uuid.UUID       `json:"consultation_id"`
	UserID         uuid.UUID       `json:"user_id"`
	DraftData      json.RawMessage `json:"draft_data"`
}

func (q *Queries) UpsertConsultationDraft(ctx context.Context, arg UpsertConsultationDraftParams) (ConsultationDraft, error) {
	row := q.db.QueryRowContext(ctx, upsertConsultationDraft,
		arg.ID,
		arg.ConsultationID,
		arg.UserID,
		arg.DraftData,
	)
	var i ConsultationDraft
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.UserID,
		&i.DraftData,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
