// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package users

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"service-admin/config"
)

type Permission struct {
	ID          string
	Value       int64
	Description string
}

var AllPermissions = []Permission{
	{ID: "ReadNotes", Value: 0x0000000000000001, Description: "Read Notes"},
	{ID: "InsertNote", Value: 0x0000000000000002, Description: "Insert Note"},
	{ID: "UpdateNote", Value: 0x0000000000000004, Description: "Update Note"},
	{ID: "DeleteNote", Value: 0x0000000000000008, Description: "Delete Note"},
	{ID: "ReadEmails", Value: 0x0000000000000040, Description: "Read Emails"},
	{ID: "SendEmail", Value: 0x0000000000000080, Description: "Send Email"},
	{ID: "ReadFiles", Value: 0x0000000000000100, Description: "Read Files"},
	{ID: "UploadFile", Value: 0x0000000000000200, Description: "Upload File"},
	{ID: "DownloadFile", Value: 0x0000000000000400, Description: "Download File"},
	{ID: "DeleteFile", Value: 0x0000000000000800, Description: "Delete File"},
	{ID: "ReadUsers", Value: 0x0000000000001000, Description: "Read Users"},
	{ID: "UpdateUser", Value: 0x0000000000002000, Description: "Update User"},
}

func UserAccessForm(cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ open: false }\" x-on:keydown.escape=\"open = false\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, templ.ComponentScript{Call: "drawer_access.showModal()"})
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button type=\"button\" class=\"btn btn-soft btn-primary\" onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.ComponentScript = templ.ComponentScript{Call: "drawer_access.showModal()"}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" @click=\"open = true\">Calculate Access</button> <dialog id=\"drawer_access\" class=\"modal modal-end\"><div class=\"modal-box max-w-xl w-full\" x-trap=\"open\"><h3 class=\"text-lg font-bold mb-10\">Edit User</h3><form id=\"calculate-access\" action=\"/users/calculate-access\" method=\"post\" enctype=\"application/x-www-form-urlencoded\" hx-boost=\"true\" hx-swap=\"none\" hx-push-url=\"false\"><fieldset><legend class=\"text-base font-semibold text-neutral-200\">Access</legend><div class=\"mt-4 divide-y divide-gray-700 border-t border-b border-gray-700\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, p := range AllPermissions {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"relative flex gap-3 py-4\"><div class=\"min-w-0 flex-1 text-sm/6\"><label for=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/users/user_access.templ`, Line: 62, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"font-medium text-neutral-200 select-none\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(p.Description)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/users/user_access.templ`, Line: 62, Col: 94}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</label></div><div class=\"flex h-6 shrink-0 items-center\"><div class=\"group grid size-4 grid-cols-1\"><input id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/users/user_access.templ`, Line: 67, Col: 21}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" name=\"access[]\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", p.Value))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/pages/users/user_access.templ`, Line: 69, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" type=\"checkbox\" checked class=\"col-start-1 row-start-1 appearance-none rounded-sm border border-gray-300 bg-white checked:border-indigo-600 checked:bg-indigo-600 indeterminate:border-indigo-600 indeterminate:bg-indigo-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:border-gray-300 disabled:bg-gray-100 disabled:checked:bg-gray-100 forced-colors:appearance-auto\"> <svg class=\"pointer-events-none col-start-1 row-start-1 size-3.5 self-center justify-self-center stroke-white group-has-disabled:stroke-gray-950/25\" viewBox=\"0 0 14 14\" fill=\"none\"><path class=\"opacity-0 group-has-checked:opacity-100\" d=\"M3 8L6 11L11 3.5\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path> <path class=\"opacity-0 group-has-indeterminate:opacity-100\" d=\"M3 7H11\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path></svg></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><div x-data=\"{\n                                        sseEvent(event) {\n                                            const detail = event.detail;\n                                            if (detail.type === 'user-access') {\n                                                document.getElementById('access').innerText = detail.data;\n                                            }\n                                        }\n                                    }\" x-on:htmx:sse-before-message.window=\"sseEvent($event)\"><div sse-swap=\"user-access\" class=\"text-center my-10 text-xl font-semibold\">Total Access Value: <span id=\"access\" class=\"font-mono\">-- calculate --</span></div></div></fieldset></form><div class=\"modal-action\"><form method=\"dialog\"><button @click=\"open = false\" class=\"btn\">Cancel</button></form><button type=\"submit\" class=\"btn btn-primary btn-soft\" form=\"calculate-access\" @click=\"open = false\"><span class=\"loading loading-spinner htmx-indicator\"></span> Calculate</button></div></div><form method=\"dialog\" class=\"modal-backdrop\"><button @click=\"open = false\">close</button></form></dialog></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
