// Command gentiers generates a TypeScript file from app/pkg/billing.TierLimits.
// It is the single source of truth for per-tier caps shared between Go and TS.
//
// Usage:
//
//	go run ./cmd/gentiers -out path/to/tier-limits.ts
//
// Or via //go:generate in app/pkg/billing/limits.go.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"app/pkg/billing"
	"app/pkg/usage"
)

func main() {
	out := flag.String("out", "", "Path to write the generated TypeScript file")
	flag.Parse()

	if *out == "" {
		fmt.Fprintln(os.Stderr, "gentiers: -out is required")
		os.Exit(2)
	}

	var buf bytes.Buffer
	writeTiers(&buf)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "gentiers: mkdir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gentiers: write: %v\n", err)
		os.Exit(1)
	}

	readmePath := filepath.Join(filepath.Dir(*out), "README.md")
	if err := os.WriteFile(readmePath, []byte(readme), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gentiers: write readme: %v\n", err)
		os.Exit(1)
	}
}

// writeTiers emits the TypeScript file deterministically.
// Iteration order: billing.SelfServeTiers (canonical), sorted feature gate keys.
func writeTiers(w *bytes.Buffer) {
	fmt.Fprintln(w, "// GENERATED FILE — DO NOT EDIT")
	fmt.Fprintln(w, "// Generated by app/cmd/gentiers from app/pkg/billing/limits.go.")
	fmt.Fprintln(w, "// Regenerate with `go generate ./...` from the app/ directory.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "export const TIER_LIMITS = {")
	for _, tier := range billing.SelfServeTiers {
		l := billing.TierLimits[tier]
		storageGB := float64(l.MaxStorageBytes) / float64(1024*1024*1024)
		fmt.Fprintf(w,
			"\t%s: { seo_audit: %d, crawl: %d, ai_generation: %d, pdf_export: %d, social_profile: %d, form: %d, max_clients: %d, max_members: %d, storage_gb: %s },\n",
			tier,
			l.SEOAudits, l.Crawls, l.AIGenerations, l.PDFExports,
			l.SocialProfiles, l.Forms,
			l.MaxClients, l.MaxMembers,
			formatGB(storageGB),
		)
	}
	fmt.Fprintln(w, "} as const;")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "export type Tier = keyof typeof TIER_LIMITS;")
	fmt.Fprintln(w, "export type UsageFeature = 'seo_audit' | 'crawl' | 'ai_generation' | 'pdf_export' | 'social_profile' | 'form';")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "export const FEATURE_GATES = {")

	// Sort feature-gate keys for deterministic output.
	gateKeys := make([]string, 0, len(usage.FeatureGate))
	for f := range usage.FeatureGate {
		gateKeys = append(gateKeys, string(f))
	}
	sort.Strings(gateKeys)
	for _, fk := range gateKeys {
		tiers := usage.FeatureGate[usage.Feature(fk)]
		fmt.Fprintf(w, "\t%s: [", fk)
		for i, t := range tiers {
			if i > 0 {
				fmt.Fprint(w, ", ")
			}
			fmt.Fprintf(w, "'%s'", t)
		}
		fmt.Fprintln(w, "],")
	}
	fmt.Fprintln(w, "} as const;")
}

// formatGB formats a storage value in GB with minimal precision —
// integers render without decimal, fractional values keep one decimal place.
func formatGB(v float64) string {
	if v == float64(int64(v)) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%.1f", v)
}

const readme = `# Generated TypeScript

**Do not edit files in this directory by hand.**

These files are generated from ` + "`app/pkg/billing/limits.go`" + ` by the
` + "`app/cmd/gentiers`" + ` tool.

To regenerate:

` + "```bash" + `
cd app && go generate ./...
` + "```" + `

CI verifies this directory is in sync with the Go source via
` + "`go generate ./... && git diff --exit-code`" + ` — if the Go source changed
and the generated TS wasn't committed, CI will fail.
`
