package export

import (
	"bytes"
	"context"
	"fmt"
	"html"
	"io"
	"mime/multipart"
	"net/http"
	"strings"
)

// exportPDF renders all copy items into a single HTML document, posts it
// to Gotenberg's Chromium HTML-to-PDF endpoint, and returns the resulting PDF.
func exportPDF(ctx context.Context, gotenbergURL string, rows []copyRow, domain string) (*ExportResult, error) {
	if gotenbergURL == "" {
		return nil, fmt.Errorf("GOTENBERG_URL not configured; PDF export unavailable")
	}

	htmlDoc := buildHTMLDocument(rows, domain)

	pdfBytes, err := convertHTMLToPDF(ctx, gotenbergURL, htmlDoc)
	if err != nil {
		return nil, fmt.Errorf("gotenberg conversion: %w", err)
	}

	return &ExportResult{
		Data:        pdfBytes,
		Filename:    domain + "-copy.pdf",
		ContentType: "application/pdf",
	}, nil
}

// buildHTMLDocument creates a self-contained HTML page with inline CSS,
// a table of contents, and each copy item as a chapter.
func buildHTMLDocument(rows []copyRow, domain string) string {
	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page { margin: 2cm; }
  body {
    font-family: 'Segoe UI', Arial, Helvetica, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a1a;
    max-width: 100%;
  }
  h1 {
    font-size: 22pt;
    color: #111;
    border-bottom: 3px solid #333;
    padding-bottom: 8px;
    margin-bottom: 24px;
  }
  h2 {
    font-size: 16pt;
    color: #222;
    margin-top: 36px;
    border-bottom: 1px solid #ccc;
    padding-bottom: 6px;
    page-break-before: always;
  }
  h2:first-of-type {
    page-break-before: avoid;
  }
  .toc {
    margin: 20px 0 40px 0;
    padding: 16px 24px;
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
  }
  .toc-title {
    font-size: 14pt;
    font-weight: bold;
    margin-bottom: 12px;
    color: #333;
  }
  .toc ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  .toc li {
    padding: 3px 0;
    font-size: 10pt;
    color: #555;
  }
  .toc li span.num {
    display: inline-block;
    width: 28px;
    color: #888;
  }
  .meta-block {
    background: #f4f6f8;
    border-left: 4px solid #4a90d9;
    padding: 8px 14px;
    margin: 8px 0 16px 0;
    font-size: 9pt;
    color: #555;
  }
  .meta-block span {
    margin-right: 18px;
  }
  .copy-content {
    white-space: pre-wrap;
    margin-bottom: 24px;
  }
  .footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #ddd;
    font-size: 8pt;
    color: #999;
    text-align: center;
  }
</style>
</head>
<body>
`)

	// Title.
	b.WriteString(fmt.Sprintf("<h1>Content Export &mdash; %s</h1>\n", html.EscapeString(domain)))

	// Table of contents.
	b.WriteString(`<div class="toc">`)
	b.WriteString(`<div class="toc-title">Table of Contents</div>`)
	b.WriteString("<ul>\n")
	for i, c := range rows {
		title := c.Title
		if title == "" {
			title = c.CopyType
		}
		b.WriteString(fmt.Sprintf(`<li><span class="num">%d.</span> %s</li>`+"\n",
			i+1, html.EscapeString(title)))
	}
	b.WriteString("</ul>\n</div>\n")

	// Each copy item as a chapter.
	for i, c := range rows {
		title := c.Title
		if title == "" {
			title = c.CopyType
		}

		b.WriteString(fmt.Sprintf("<h2>%d. %s</h2>\n", i+1, html.EscapeString(title)))

		// Metadata block.
		b.WriteString(`<div class="meta-block">`)
		b.WriteString(fmt.Sprintf(`<span><strong>Type:</strong> %s</span>`, html.EscapeString(c.CopyType)))
		b.WriteString(fmt.Sprintf(`<span><strong>Status:</strong> %s</span>`, html.EscapeString(c.Status)))
		b.WriteString(fmt.Sprintf(`<span><strong>Words:</strong> %d</span>`, c.ActualWordCount))
		if c.TargetKeyword.Valid && c.TargetKeyword.String != "" {
			b.WriteString(fmt.Sprintf(`<span><strong>Keyword:</strong> %s</span>`,
				html.EscapeString(c.TargetKeyword.String)))
		}
		b.WriteString("</div>\n")

		// Content.
		b.WriteString(`<div class="copy-content">`)
		b.WriteString(html.EscapeString(c.Content))
		b.WriteString("</div>\n")
	}

	// Footer.
	b.WriteString(`<div class="footer">`)
	b.WriteString(fmt.Sprintf("Generated by Webkit &mdash; %d content items", len(rows)))
	b.WriteString("</div>\n")

	b.WriteString("</body>\n</html>")
	return b.String()
}

// convertHTMLToPDF posts the HTML document to Gotenberg's Chromium endpoint
// and returns the PDF bytes.
func convertHTMLToPDF(ctx context.Context, gotenbergURL, htmlContent string) ([]byte, error) {
	// Gotenberg expects a multipart form with a file named index.html.
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)

	part, err := writer.CreateFormFile("files", "index.html")
	if err != nil {
		return nil, fmt.Errorf("creating form file: %w", err)
	}
	if _, err := part.Write([]byte(htmlContent)); err != nil {
		return nil, fmt.Errorf("writing html content: %w", err)
	}

	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("closing multipart writer: %w", err)
	}

	endpoint := strings.TrimRight(gotenbergURL, "/") + "/forms/chromium/convert/html"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, &body)
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("posting to gotenberg: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gotenberg returned %d: %s", resp.StatusCode, string(respBody))
	}

	pdfBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading gotenberg response: %w", err)
	}

	return pdfBytes, nil
}
