version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - funlen
    - gocognit
    - goconst
    - godot
    - lll
    - mnd
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
    - wsl_v5
    - funcorder
    - noctx
  settings:
    exhaustive:
      ignore-enum-members: stripe.*
    exhaustruct:
      exclude:
        - net/.*
        - github.com/stripe/stripe-go/.*
        - github.com/aws/aws-sdk-go-v2/.*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - '(.+)_templ\.go'
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
